# Generated by Django 3.0 on 2019-12-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialieven', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularPizza',
        ),
    ]
