# Generated by Django 3.0 on 2019-12-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialieven', '0005_auto_20191210_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiteit',
            options={'ordering': ['datum']},
        ),
    ]
