# Generated by Django 3.0 on 2019-12-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialieven', '0007_auto_20191211_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aanmelding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialieven.Activiteit')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
