# Generated by Django 2.2.7 on 2019-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_count_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='category',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
