# Generated by Django 2.2.7 on 2019-11-25 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_item_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_item',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='regular_pizza',
            new_name='RegularPizza',
        ),
        migrations.RenameModel(
            old_name='sicilian_pizza',
            new_name='SicilianPizza',
        ),
    ]
