# Generated by Django 2.2.7 on 2019-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191126_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_topping',
        ),
    ]
