# Generated by Django 3.0 on 2019-12-05 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191205_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='straat',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
