# Generated by Django 3.0 on 2019-12-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191205_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Huisnummer',
            new_name='huisnummer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Woonplaats',
            new_name='woonplaats',
        ),
    ]
