# Generated by Django 3.0 on 2019-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191210_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='huisnummer',
            field=models.IntegerField(),
        ),
    ]
