# Generated by Django 3.0 on 2019-12-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191210_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='geboortedatum',
            field=models.CharField(max_length=10),
        ),
    ]
