# Generated by Django 3.0 on 2019-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191210_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Straat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straatnaam', models.CharField(max_length=256)),
            ],
        ),
    ]
