# Generated by Django 2.2.7 on 2019-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_selected_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_topping',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
