# Generated by Django 2.2.7 on 2019-11-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_selected_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topping1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping3',
            field=models.CharField(default='', max_length=64),
        ),
    ]
