# Generated by Django 2.2.7 on 2019-11-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_topping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='topping3',
        ),
    ]
