# Generated by Django 3.0 on 2019-12-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialieven', '0002_delete_regularpizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('datum', models.DateField()),
                ('starttijd', models.CharField(max_length=5)),
                ('eindtijd', models.CharField(max_length=5)),
                ('straat', models.CharField(max_length=64)),
                ('huisnummer', models.IntegerField()),
                ('postcode', models.CharField(max_length=6)),
                ('plaats', models.CharField(max_length=64)),
                ('gebouw', models.IntegerField(blank=True)),
                ('verdieping', models.IntegerField(blank=True)),
                ('categorie', models.CharField(max_length=64)),
                ('uitgenodigd', models.BooleanField()),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
