# Generated by Django 3.0 on 2019-12-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialieven', '0003_activiteit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteit',
            name='beschrijving',
            field=models.CharField(default='beschrijving', max_length=2048),
            preserve_default=False,
        ),
    ]
