# Generated by Django 3.0 on 2019-12-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialieven', '0008_aanmelding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aanmelding',
            options={'ordering': ['activiteit']},
        ),
    ]
